### ISSUE TITLE
Ошибка с LongPoll

### ISSUE THREAD

**Issue by dvec** [python273/vk_api#111]
```python
from vk_api import VkApi
from vk_api.longpoll import VkLongPoll

sess = VkApi(token='secret')
lp = VkLongPoll(sess, mode=8)
# С mode=32 все работает

for event in lp.listen():
    print(event)
```
Как только vk возращает какой-нибудь event, вылетает ошибка
```
Traceback (most recent call last):
  File "/home/dvec/PycharmProjects/untitled/main.py", line 7, in <module>
    for event in lp.listen():
  File "/home/dvec/PycharmProjects/untitled/venv/lib/python3.5/site-packages/vk_api/longpoll.py", line 212, in listen
    for event in events:
  File "/home/dvec/PycharmProjects/untitled/venv/lib/python3.5/site-packages/vk_api/longpoll.py", line 193, in check
    self.pts = response['pts']
KeyError: 'pts'
```

**Comment by Helow19274** [comment]
![default](https://user-images.githubusercontent.com/20171143/39207897-e0626ac6-4809-11e8-9865-95c9d5e3f70c.png)
Всё работает нормально
