### ISSUE TITLE
Пример proxies_timeout_retries.py не работает

### ISSUE THREAD

**Issue by dzmitrymaliuzhenets** [python273/vk_api#126]
Пример proxies_timeout_retries.py не работает- выбрасывается исключение:

```
Traceback (most recent call last):
  File "/home/dzmitry/PycharmProjects/VkCreator/statictics.py", line 30, in <module>
    main()
  File "/home/dzmitry/PycharmProjects/VkCreator/statictics.py", line 25, in main
    vk_session.http.mount('https://', MyHTTPAdapter(max_retries=10, timeout=8))
  File "/home/dzmitry/PycharmProjects/VkCreator/statictics.py", line 9, in __init__
    super(MyHTTPAdapter, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeout'
```

**Comment by python273** [comment]
Думаю будет работать с 
`self.timeout = kwargs['timeout']`
->
`self.timeout = kwargs.pop('timeout', None)`

**Comment by dzmitrymaliuzhenets** [comment]
Да, теперь все работает
