### ISSUE TITLE
 UnicodeDecodeError:

### ISSUE THREAD

**Issue by dimared** [python273/vk_api#185]
Сервер на Убунте, версия питона 3.5.2, pip 18.0
Запуская команду pip3 install vk_api
Ошибка:
```
Collecting vk_api
  Downloading https://files.pythonhosted.org/packages/dc/80/843067681acfd2538bec31eeff6e4208c122ab9149d370f285a4ba6464c5/vk_api-11.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-udzh4y87/vk-api/setup.py", line 16, in <module>
        long_description = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 193: ordinal not in range(128)
```
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-udzh4y87/vk-api/`

**Comment by Helow19274** [comment]
Попробуйте из репозитория установить, должно работать. Фикса ещё в релизе нет

**Comment by dimared** [comment]
Я так и сделал, спасибо. 
Поправил setup.py, убрав строчки
```
with open('README.md', encoding='utf-8') as f:
    long_description = f.read()
```
и добавив 
`long_description = ""`
