### ISSUE TITLE
Крашатся эвенты

### ISSUE THREAD

**Issue by Andryshik345** [python273/vk_api#188]
После обновления либы на версию 11.2 начали крашаться эвенты user_id и chat_id при получении событий лонгполла из бесед, причем не только в моем скрипте, но я специально даже проверил на вашем экзампле (example/longpoll.py) и там тоже вылетело(скрин как раз оттуда)
![default](https://user-images.githubusercontent.com/24612088/46417525-4ccc6500-c743-11e8-976e-c1e2b6ee1d6c.png)

**Comment by python273** [comment]
Можешь проверить фикс в #189?

**Comment by Andryshik345** [comment]
Сначала вроде работало, но потом снова крашнулось
```
Печатает  198280981 в беседе 38
Печатает  386277338 в беседе 30
Пользователь 62938995 оффлайн VkOfflineType.AWAY
Пользователь 192401668 оффлайн VkOfflineType.AWAY
Новое сообщение:
Для меня от: 386277338 в беседе 30
Текст:  Мне надо хотя бы это понять

Traceback (most recent call last):
  File "test.py", line 76, in <module>
    main()
  File "test.py", line 34, in main
    for event in longpoll.listen():
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 595, in listen
    for event in self.check():
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 544, in check
    for raw_event in response['updates']
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 544, in <listcomp>
    for raw_event in response['updates']
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 498, in _parse_event
    return self.DEFAULT_EVENT_CLASS(raw_event)
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 355, in __init__
    self._parse_peer_id()
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 404, in _parse_peer_id
    if 'from' in self.extra_values:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by python273** [comment]
Можешь добавить
```
        print(event.type)
        print(event.raw)
```
После `for event in longpoll.listen():` и скинуть когда еще раз упадет?

**Comment by Andryshik345** [comment]
Держи
```
VkEventType.USER_OFFLINE
[9, -46003497, 1, 1538593005]
Пользователь 46003497 оффлайн VkOfflineType.AWAY
VkEventType.USER_OFFLINE
[9, -386277338, 0, 1538593290]
Пользователь 386277338 оффлайн VkOfflineType.EXIT
VkEventType.USER_OFFLINE
[9, -145170120, 0, 1538593304]
Пользователь 145170120 оффлайн VkOfflineType.EXIT
VkEventType.USER_ONLINE
[8, -386277338, 4, 1538593299]
Пользователь 386277338 онлайн VkPlatform.ANDROID
VkEventType.USER_TYPING_IN_CHAT
[62, 265762564, 30]
Печатает  265762564 в беседе 30
Traceback (most recent call last):
  File "test.py", line 79, in <module>
    main()
  File "test.py", line 34, in main
    for event in longpoll.listen():
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 595, in listen
    for event in self.check():
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 544, in check
    for raw_event in response['updates']
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 544, in <listcomp>
    for raw_event in response['updates']
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 498, in _parse_event
    return self.DEFAULT_EVENT_CLASS(raw_event)
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 355, in __init__
    self._parse_peer_id()
  File "C:\Users\Андрей\AppData\Local\Programs\Python\Python36-32\lib\site-packages\vk_api\longpoll.py", line 404, in _parse_peer_id
    if 'from' in self.extra_values:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by python273** [comment]
Понял в чем проблема, сейчас должно быть окей в #189

**Comment by Andryshik345** [comment]
Да, тестил несколько часов, больше не вылетало, можешь мерджить и закрывать
