### ISSUE TITLE
ReadTimeout

### ISSUE THREAD

**Issue by Nix1304** [python273/vk_api#197]
https://github.com/Nix1304/Ignis-Samurai/blob/master/bot.py
при засыпании пк на некоторое время, после 35 секунд после пробуждения я получаю ошибку. вот полный лог
`Traceback (most recent call last):
File "/Volumes/Files/Projects/Ignis Samurai/bot.py", line 190, in <module>
bot.longpoll_run()
File "/Volumes/Files/Projects/Ignis Samurai/bot.py", line 114, in longpoll_run
self.loop.run_until_complete(self.main_task)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
return future.result()
File "/Volumes/Files/Projects/Ignis Samurai/bot.py", line 130, in listen_longpoll
for event in longpoll.listen():
File "/Users/nix13/venv/lib/python3.6/site-packages/vk_api/bot_longpoll.py", line 274, in listen
for event in self.check():
File "/Users/nix13/venv/lib/python3.6/site-packages/vk_api/bot_longpoll.py", line 246, in check
timeout=self.wait + 10
File "/Users/nix13/venv/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
return self.request('GET', url, **kwargs)
File "/Users/nix13/venv/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/Users/nix13/venv/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/Users/nix13/venv/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='lp.vk.com', port=443): Read timed out. (read timeout=35)`

**Comment by python273** [comment]
https://github.com/python273/vk_api/issues/144#issuecomment-404023710

**Comment by Nix1304** [comment]
спасибо, помогло
