### ISSUE TITLE
Не работает bot_longpoll.

### ISSUE THREAD

**Issue by 0xBFFFF0A4** [python273/vk_api#202]
`Traceback (most recent call last):
  File "uebot.py", line 13, in <module>
    listen(vk_api, token, group_id)
  File "uebot.py", line 10, in listen
    for event in longpool.listen():
  File "/usr/local/lib/python3.6/dist-packages/vk_api/bot_longpoll.py", line 274, in listen
    for event in self.check():
  File "/usr/local/lib/python3.6/dist-packages/vk_api/bot_longpoll.py", line 253, in check
    for raw_event in response['updates']
  File "/usr/local/lib/python3.6/dist-packages/vk_api/bot_longpoll.py", line 253, in <listcomp>
    for raw_event in response['updates']
  File "/usr/local/lib/python3.6/dist-packages/vk_api/bot_longpoll.py", line 214, in _parse_event
    return event_class(raw_event)
  File "/usr/local/lib/python3.6/dist-packages/vk_api/bot_longpoll.py", line 160, in __init__
    if self.obj.peer_id < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
`

**Comment by python273** [comment]
https://github.com/python273/vk_api/issues/174#issuecomment-426396218
