### ISSUE TITLE
Type error for bot_longpoll

### ISSUE THREAD

**Issue by Arsen-chechen** [python273/vk_api#225]
When I launch a bot in my group in the example bot_longpoll and write a message to the group, I get a "  File "C:\Program Files (x86)\Python37-32\lib\site-packages\vk_api\bot_longpoll.py", line 160, in __init__
    if self.obj.peer_id < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'"
Python v3.7.2

**Comment by Arsen-chechen** [comment]
init it means `__ init __`

**Comment by Sergey-Volchkov** [comment]
Покажите код, который отвечает за отправку сообщения в группу

**Comment by Arsen-chechen** [comment]
Я руками в группу писал со своей страницы, из браузера.

**Comment by Arsen-chechen** [comment]
А принимал сообщения кодом из examples/bot_longpoll.py, если Вы спрашиваете об этом.

**Comment by Sergey-Volchkov** [comment]
Покажите ваш код который вы используете для принятия сообщения
Сложно сказать что не так, не видя исходник

**Comment by Arsen-chechen** [comment]
Попробовал на версии 3.5.4, вылетает такая же ошибка. Привожу полный текст `Traceback (most recent call last):
  File "main.py", line 44, in <module>
    main()
  File "main.py", line 36, in main
    token=group_api, group_id=group_id
  File "main.py", line 19, in auth_and_handle
    for event in longpoll.listen():
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\vk_api\bot_longpoll.py", line 274, in listen
    for event in self.check():
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\vk_api\bot_longpoll.py", line 253, in check
    for raw_event in response['updates']
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\vk_api\bot_longpoll.py", line 253, in <listcomp>
    for raw_event in response['updates']
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\vk_api\bot_longpoll.py", line 214, in _parse_event
    return event_class(raw_event)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\vk_api\bot_longpoll.py", line 160, in __init__
    if self.obj.peer_id < 0:
TypeError: unorderable types: NoneType() < int()`

Не могли бы Вы уточнить версию Python до третьей цифры, на которой у вас всё работает?

**Comment by ALEXREDX** [comment]
У меня на 3.7.0 работает, не думаю что это зависит от версии.
В группе какая версия апи стоит? Пересоздать токен пробовал?
