### ISSUE TITLE
Сломалась библиотека через день использования (AttributeError: module 'http.cookiejar' has no attribute 'CookieJar')

### ISSUE THREAD

**Issue by VerbleHack** [python273/vk_api#234]
Привет! Использую эту библиотеку уже день и вот только что на коде, который работал несколько секунд назад сыпятся ошибки:
```
Traceback (most recent call last):
  File "./copy.py", line 4, in <module>
    import vk_api
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/__init__.py", line 10, in <module>
    from .requests_pool import VkRequestsPool, vk_request_one_param_pool
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/requests_pool.py", line 14, in <module>
    from .execute import VkFunction
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/execute.py", line 11, in <module>
    from .utils import sjson_dumps
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/utils.py", line 21, in <module>
    from http.cookiejar import Cookie
  File "/usr/lib/python3.5/http/cookiejar.py", line 31, in <module>
    import copy
  File "/home/cheater/Документы/copy.py", line 5, in <module>
    from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/bot_longpoll.py", line 10, in <module>
    import requests
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/utils.py", line 32, in <module>
    from .cookies import cookiejar_from_dict
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/cookies.py", line 171, in <module>
    class RequestsCookieJar(cookielib.CookieJar, MutableMapping):
AttributeError: module 'http.cookiejar' has no attribute 'CookieJar'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 15, in <module>
    import xml.dom, xml.dom.minidom
  File "/usr/lib/python3.5/xml/dom/minidom.py", line 23, in <module>
    from xml.dom.xmlbuilder import DOMImplementationLS, DocumentLS
  File "/usr/lib/python3.5/xml/dom/xmlbuilder.py", line 3, in <module>
    import copy
  File "/home/cheater/Документы/copy.py", line 4, in <module>
    import vk_api
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/__init__.py", line 10, in <module>
    from .requests_pool import VkRequestsPool, vk_request_one_param_pool
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/requests_pool.py", line 14, in <module>
    from .execute import VkFunction
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/execute.py", line 12, in <module>
    from .vk_api import VkApi, VkApiMethod
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/vk_api.py", line 15, in <module>
    import requests
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/utils.py", line 32, in <module>
    from .cookies import cookiejar_from_dict
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/cookies.py", line 171, in <module>
    class RequestsCookieJar(cookielib.CookieJar, MutableMapping):
AttributeError: module 'http.cookiejar' has no attribute 'CookieJar'

Original exception was:
Traceback (most recent call last):
  File "./copy.py", line 4, in <module>
    import vk_api
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/__init__.py", line 10, in <module>
    from .requests_pool import VkRequestsPool, vk_request_one_param_pool
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/requests_pool.py", line 14, in <module>
    from .execute import VkFunction
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/execute.py", line 11, in <module>
    from .utils import sjson_dumps
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/utils.py", line 21, in <module>
    from http.cookiejar import Cookie
  File "/usr/lib/python3.5/http/cookiejar.py", line 31, in <module>
    import copy
  File "/home/cheater/Документы/copy.py", line 5, in <module>
    from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/bot_longpoll.py", line 10, in <module>
    import requests
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/utils.py", line 32, in <module>
    from .cookies import cookiejar_from_dict
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/cookies.py", line 171, in <module>
    class RequestsCookieJar(cookielib.CookieJar, MutableMapping):
AttributeError: module 'http.cookiejar' has no attribute 'CookieJar'
```
Сам код:
```
#!/usr/bin/python3.5
# -*- coding: utf-8 -*-
import time
import vk_api
from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType
from vk_api.utils import get_random_id

def main():
		vk_session = vk_api.VkApi(token='токен - это личное :)')
		vk = vk_session.get_api()
		longpoll = VkBotLongPoll(vk_session, 'id группы')

		for event in longpoll.listen():

				if event.obj.text == '[clubИД|*ИД] ответь':
					vk.messages.send(
						random_id=get_random_id(),
						#chat_id = 111,
						peer_id = 2000000111,
						message='Heh'
						)

if __name__ == '__main__':
	main()
```
Что я делаю не так? xD

**Comment by python273** [comment]
Попробуй обновить requests

**Comment by VerbleHack** [comment]
> Попробуй обновить requests
Обновил, ошибка та же.
Лог обновления:
```
python3.5 -m pip install requests --upgrade
Collecting requests
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Installing collected packages: chardet, urllib3, certifi, idna, requests
Successfully installed certifi-2019.3.9 chardet-3.0.4 idna-2.8 requests-2.21.0 urllib3-1.24.1

```

**Comment by python273** [comment]
Какие `.py` файлы есть в папке с `copy.py`?

**Comment by VerbleHack** [comment]
> Какие `.py*` файлы есть в папке с `copy.py`?

`copy.py` - сам скрипт :)

**Comment by python273** [comment]
```
  File "/usr/lib/python3.5/http/cookiejar.py", line 31, in <module>
    import copy
  File "/home/cheater/Документы/copy.py", line 5, in <module>
    from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType
```
переименуй файл

**Comment by VerbleHack** [comment]
> ```
>   File "/usr/lib/python3.5/http/cookiejar.py", line 31, in <module>
>     import copy
>   File "/home/cheater/Документы/copy.py", line 5, in <module>
>     from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType
> ```
> переименуй файл

С `copy.py` помогло, а вот с `2pb.py` (сейчас `VkBotSimpleExampleBLOBLOBLOLAL.py`) не помогло:
```
./VkBotSimpleExampleBLOBLOBLOLAL.py
Traceback (most recent call last):
  File "./VkBotSimpleExampleBLOBLOBLOLAL.py", line 5, in <module>
    import vk_api
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/__init__.py", line 10, in <module>
    from .requests_pool import VkRequestsPool, vk_request_one_param_pool
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/requests_pool.py", line 14, in <module>
    from .execute import VkFunction
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/execute.py", line 11, in <module>
    from .utils import sjson_dumps
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/utils.py", line 21, in <module>
    from http.cookiejar import Cookie
  File "/usr/lib/python3.5/http/cookiejar.py", line 31, in <module>
    import copy
  File "/home/cheater/Документы/copy.py", line 5, in <module>
    from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/bot_longpoll.py", line 10, in <module>
    import requests
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/utils.py", line 32, in <module>
    from .cookies import cookiejar_from_dict
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/cookies.py", line 171, in <module>
    class RequestsCookieJar(cookielib.CookieJar, MutableMapping):
AttributeError: module 'http.cookiejar' has no attribute 'CookieJar'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 15, in <module>
    import xml.dom, xml.dom.minidom
  File "/usr/lib/python3.5/xml/dom/minidom.py", line 23, in <module>
    from xml.dom.xmlbuilder import DOMImplementationLS, DocumentLS
  File "/usr/lib/python3.5/xml/dom/xmlbuilder.py", line 3, in <module>
    import copy
  File "/home/cheater/Документы/copy.py", line 4, in <module>
    import vk_api
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/__init__.py", line 10, in <module>
    from .requests_pool import VkRequestsPool, vk_request_one_param_pool
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/requests_pool.py", line 14, in <module>
    from .execute import VkFunction
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/execute.py", line 12, in <module>
    from .vk_api import VkApi, VkApiMethod
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/vk_api.py", line 15, in <module>
    import requests
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/utils.py", line 32, in <module>
    from .cookies import cookiejar_from_dict
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/cookies.py", line 171, in <module>
    class RequestsCookieJar(cookielib.CookieJar, MutableMapping):
AttributeError: module 'http.cookiejar' has no attribute 'CookieJar'

Original exception was:
Traceback (most recent call last):
  File "./VkBotSimpleExampleBLOBLOBLOLAL.py", line 5, in <module>
    import vk_api
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/__init__.py", line 10, in <module>
    from .requests_pool import VkRequestsPool, vk_request_one_param_pool
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/requests_pool.py", line 14, in <module>
    from .execute import VkFunction
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/execute.py", line 11, in <module>
    from .utils import sjson_dumps
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/utils.py", line 21, in <module>
    from http.cookiejar import Cookie
  File "/usr/lib/python3.5/http/cookiejar.py", line 31, in <module>
    import copy
  File "/home/cheater/Документы/copy.py", line 5, in <module>
    from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType
  File "/home/cheater/.local/lib/python3.5/site-packages/vk_api/bot_longpoll.py", line 10, in <module>
    import requests
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/utils.py", line 32, in <module>
    from .cookies import cookiejar_from_dict
  File "/home/cheater/.local/lib/python3.5/site-packages/requests/cookies.py", line 171, in <module>
    class RequestsCookieJar(cookielib.CookieJar, MutableMapping):
AttributeError: module 'http.cookiejar' has no attribute 'CookieJar'
```

**Comment by python273** [comment]
у тебя не должно быть `copy.py` файла в папке

**Comment by VerbleHack** [comment]
> у тебя не должно быть `copy.py` файла в папке

Да, точно &#128563;!
Спасибо большое, вопрос закрыт :)
