### ISSUE TITLE
Исключение KeyError: 'ts'

### ISSUE THREAD

**Issue by Xokare** [python273/vk_api#242]
По неизвестным науке причинам, примерно раз в сутки, ночью приходит исключение

>Main [INFO] - 2019-05-02 02:20:07.606110+03:00
> Exception [ERROR] - 'ts'
> Exception [ERROR] - Traceback text: 
> Traceback (most recent call last):
>   File "vk_logs.py", line 192, in <module>
>     main()
>   File "vk_logs.py", line 45, in main
>     for event in longpoll.listen():
>   File "/app/.heroku/python/lib/python3.7/site-packages/vk_api/longpoll.py", line 603, in listen
>     for event in self.check():
>   File "/app/.heroku/python/lib/python3.7/site-packages/vk_api/longpoll.py", line 546, in check
>     self.ts = response['ts']
> KeyError: 'ts'

**Comment by Xokare** [comment]
Судя по всему, проблема с вк апи, а именно кривым ответом
