### ISSUE TITLE
Поиск аудио - AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by Deezyq** [python273/vk_api#244]
```
tracks = vkaudio.search(q='guetta', count=10)

for n, track in enumerate(tracks, 1):
    print('{}. {} {}'.format(n, track['title'], track['url']))
```

Получаю:
```
Traceback (most recent call last):
  File "start.py", line 21, in <module>
    for n, track in enumerate(tracks, 1):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vk_api/audio.py", line 205, in search_iter
    tracks = scrap_data(response.text, self.user_id)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vk_api/audio.py", line 236, in scrap_data
    for audio in root_el.find_all('div', {'class': 'audio_item'}):
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by python273** [comment]
У меня не падает, может библиотека не обновлена. Но результат пустой для `guetta`

**Comment by Deezyq** [comment]
Решил. Подключился через логин:пароль, все заработало. Через токен не работал.
