### ISSUE TITLE
user longpool

### ISSUE THREAD

**Issue by apepenkov** [python273/vk_api#271]
vk_api.exceptions.ApiError: [15] Access denied: no access to call this method
 Не работает лонгпул для юзера, код абсолютно как в примере https://github.com/python273/vk_api/blob/master/examples/longpoll.py

**Comment by apepenkov** [comment]
Traceback (most recent call last):
  File "C:/projects/vkbot/BOT.py", line 65, in <module>
    main()
  File "C:/projects/vkbot/BOT.py", line 21, in main
    longpoll = VkLongPoll(vk_session)
  File "C:\projects\vkbot\venv\lib\site-packages\vk_api\longpoll.py", line 503, in __init__
    self.update_longpoll_server()
  File "C:\projects\vkbot\venv\lib\site-packages\vk_api\longpoll.py", line 513, in update_longpoll_server
    response = self.vk.method('messages.getLongPollServer', values)
  File "C:\projects\vkbot\venv\lib\site-packages\vk_api\vk_api.py", line 636, in method
    raise error
vk_api.exceptions.ApiError: [15] Access denied: no access to call this method

**Comment by ALEXREDX** [comment]
https://github.com/python273/vk_api/issues/219

**Comment by drygdryg** [comment]
При получении ток на в настройках сообщество нужно дать не только доступ к сообщениям, но и к управлению сообществом.![](https://i.imgur.com/uYE2YNm.jpg)

**Comment by apepenkov** [comment]
User лонг пул

вс, 7 июл. 2019 г., 20:40 Victor <notifications@github.com>:
