### ISSUE TITLE
Ошибка при создании кнопки VK Pay

### ISSUE THREAD

**Issue by odmen27** [python273/vk_api#277]
Пишу бота на Python и добавляю кнопку VK Pay:

```
      keyboard = VkKeyboard(one_time=True)
      keyboard.add_vkpay_button(hash='action=transfer-to-group&group_id=149710092')

      vk.messages.send(
          peer_id = event.object.from_id,
          random_id=get_random_id(),
          keyboard = keyboard.get_keyboard(),
          message="Кнопка VK Pay"
      )
```
Но... что-то идёт не по плану :)
```
Traceback (most recent call last):
  File "longpoll.py", line 374, in <module>
    main()
  File "longpoll.py", line 273, in main
    keyboard.add_vkpay_button('action=transfer-to-group&group_id=149710092')
AttributeError: 'VkKeyboard' object has no attribute 'add_vkpay_button'
```

Библиотеку обновил до последней версии. Никаких проблем до этого не возникало, текстовые кнопки работают нормально, а вот с location и vkpay всё печально :c 

В чём может быть проблема?

**Comment by python273** [comment]
Скорее всего библиотека не обновлена. Версию можно посмотреть через:
```python
import vk_api
print(vk_api.__version__)
```
