### ISSUE TITLE
Ошибки при VkTools..

### ISSUE THREAD

**Issue by mstiya** [python273/vk_api#286]
```
Traceback (most recent call last):
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\vk_api\tools.py", line 67, in get_all_iter
    offset_mul=-1 if negative_offset else 1
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\vk_api\execute.py", line 66, in __call__
    raw=self.return_raw
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\vk_api\vk_api.py", line 640, in method
    raise error
vk_api.exceptions.ApiError: [13] Runtime error occurred during code invocation: Method slice requires an array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app/get_wall.py", line 43, in <module>
    main()
  File "app/get_wall.py", line 31, in main
    wall = tools.get_all('wall.get', 100, {'owner_id': 1})
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\vk_api\tools.py", line 105, in get_all
    method, max_count, values, key, limit, stop_fn, negative_offset
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\vk_api\tools.py", line 71, in get_all_iter
    'Can\'t load items. Check access to requested items'
vk_api.exceptions.VkToolsException: Can't load items. Check access to requested items
```
Всё было нормально, но час назад появилось это.

**Comment by prostomarkeloff** [comment]
Ошибку читать пробовали?;)

**Comment by mstiya** [comment]
> Ошибку читать пробовали?;)

Но ведь этот код скопирован полностью с гитхаба...
Если что-то знаете, то подскажите, пожалуйста.

**Comment by python273** [comment]
Есть точно как в примере, то не уверен в чем проблема. Простой способ проверить - вызвать `wall.get` обычным способом, наверное какую-то ошибку вернет
```python
vk = vk_session.get_api()
print(vk.wall.get(owner_id=1))
```

**Comment by CounterPill** [comment]
Актуальные лимиты на методы:
newsfeed.search — 1000 вызовов в сутки;
wall.search — 1000 вызовов в сутки;
wall.get — 5000 вызовов в сутки. 

https://vk.com/dev/data_limits
