### ISSUE TITLE
Исключение от реквестов стабильно раз в сутки

### ISSUE THREAD

**Issue by P2LOVE** [python273/vk_api#302]
```
Traceback (most recent call last):
  File "/home/p2love/main.py", line 148, in <module>
    for event in longpoll.listen():
  File "/home/p2love/.local/lib/python3.7/site-packages/vk_api/longpoll.py", line 621, in listen
    for event in self.check():
  File "/home/p2love/.local/lib/python3.7/site-packages/vk_api/longpoll.py", line 560, in check
    timeout=self.wait + 10
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='im.vk.com', port=443): Read timed out. (read timeout=35)
```

Ловлю такой трейсбек каждую ночь. Использую юзертокен.
Судя по всему вк ребутает серваки и коннект отваливается в исключение.

Планируются фиксы или надо в try оборачивать всё?

**Comment by prostomarkeloff** [comment]
Было бы неплохо обернуть запрос внутри библиотеки в try except. Пока кроме как своего блока try-except делать нечего.

**Comment by dadyarri** [comment]
Единственное, что можно сделать переопределить класс longpoll`а: #144
