### ISSUE TITLE
Ошибка в VkAudio

### ISSUE THREAD

**Issue by madcrinkle** [python273/vk_api#311]
vk_session = vk_api.VkApi(login, passwd, scope=scope)
vk_session.auth()
tracks = VkAudio(vk_session).get(owner_id=80000000)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vk_api\audio.py", line 96, in get
    return list(self.get_iter(owner_id, album_id, access_hash))
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vk_api\audio.py", line 77, in get_iter
    filter_root_el={'class_': 'audioPlaylist__list'} if album_id else None
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vk_api\audio.py", line 244, in scrap_data
    int(i) for i in RE_AUDIO_ID.search(audio['id']).groups()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bs4\element.py", line 1016, in __getitem__
    return self.attrs[key]
KeyError: 'id'

**Comment by Milkiweed** [comment]
Аналогичная проблема, кажется вк обновили html структуру и bs4 не может подтянуть дату :(

```self = <div class="audio_item audio_item audio_item_560237477_456239299 ai_has_btn" data-audio='[456239299,560237477,"https:\...">
<div class="aic_slider" onclick="cancelEvent(event);"></div>
</div>
</div>
</div>
</td>
</tr>
</table>
</div>
</div>
key = 'id'
```

**Comment by madcrinkle** [comment]
Спасибо! Все заработало!
