### ISSUE TITLE
Ошибка в VkStreaming (TypeError: __call__() takes 1 positional argument but 2 were given)

### ISSUE THREAD

**Issue by LulzLoL231** [python273/vk_api#341]
_При попытке инициализации класса VkStreaming поднимается TypeError_

### Окружение

vk_api: _11.6.1_

API: _5.92_

Способ авторизации: _Implict Flow_

### Пример кода с ошибкой

(vk – объект класса VkApiMethod)
```python
def GetStream(vk):
    stream = VkStreaming(vk)
    return stream
```

### Traceback
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/User/Documents/Python/py/lib/python3.7/site-packages/vk_api/streaming.py", line 33, in __init__
    self.update_streaming_server()
  File "/Users/User/Documents/Python/py/lib/python3.7/site-packages/vk_api/streaming.py", line 36, in update_streaming_server
    response = self.vk.method('streaming.getServerUrl')
TypeError: __call__() takes 1 positional argument but 2 were given
```

**Comment by LulzLoL231** [comment]
Всё, понял свою ошибку, нужно было передать объект класса `VkApi`, а не `VkApiMethod`
