### ISSUE TITLE
Access denied: no access to call this method BotLongPoll

### ISSUE THREAD

**Issue by Jeeeeeeeeeja** [python273/vk_api#354]
В группе включил longpoll, проставил ивенты, получил токен на сообщения. Выходит ошибка:
```python
Traceback (most recent call last):
  File "C:/Users/arseniy/PycharmProjects/bot_kwork/main.py", line 141, in <module>
    main(keyboard, keyboard2, keyboard3)
  File "C:/Users/arseniy/PycharmProjects/bot_kwork/main.py", line 104, in main
    longpoll = VkBotLongPoll(bot, groupid)
  File "C:\Users\arseniy\Anaconda\envs\bot_kwork\lib\site-packages\vk_api\bot_longpoll.py", line 218, in __init__
    self.update_longpoll_server()
  File "C:\Users\arseniy\Anaconda\envs\bot_kwork\lib\site-packages\vk_api\bot_longpoll.py", line 231, in update_longpoll_server
    response = self.vk.method('groups.getLongPollServer', values)
  File "C:\Users\arseniy\Anaconda\envs\bot_kwork\lib\site-packages\vk_api\vk_api.py", line 646, in method
    raise error
vk_api.exceptions.ApiError: [15] Access denied: no access to call this method
```
![image](https://user-images.githubusercontent.com/10745893/80421646-7a5c9e80-88e5-11ea-8699-475ec63851ee.png)
![image](https://user-images.githubusercontent.com/10745893/80421658-8183ac80-88e5-11ea-8cb1-968d5efa5eb5.png)

### Окружение

vk_api:11.8.0

API: 5.95

### Пример

```python
    bot = vk_api.VkApi(token=TOKEN)
    longpoll = VkBotLongPoll(bot, groupid)
    vk = bot.get_api()
```

**Comment by Jeeeeeeeeeja** [comment]
После создания токена со всеми правами проблема решилась
