### ISSUE TITLE
При попытке авторизоваться вызывается исключение.

### ISSUE THREAD

**Issue by Pcholken** [python273/vk_api#398]
Могу предположить что проблема с парсингом ссылки. 
`https://vk.com/login.php?act=auth_redirect&app_id=6222115&authorize_url=https%3A%2F%2Foauth.vk.com%2Fblank.html%23access_token%3D XX %26expires_in%3D0%26user_id%3D651926068&redirect_hash=8252f7dboeb67a7d1a`, такого вида она приходит.
И вот так выглядит парсинг
```python
params = response.url.split('#', 1)[1].split('&')
token = dict(param.split('=', 1) for param in params)
```

### Окружение

vk_api: 11.9.1

API: 5.92

### Пример

```python
def vk_auth(proxy, login=None, password=None):
    vk_session = vk_api.VkApi(login=login, password=password)
    vk_session.http.proxies = {
        "http": f"http://{proxy}",
        "https": f"http://{proxy}"
    }
    if login and password is not None:
        vk_session.auth()
    return vk_session.get_api()
```

```python
Traceback (most recent call last):
  File "/home/pcholken/.local/lib/python3.9/site-packages/vk_api/vk_api.py", line 173, in auth
    self._auth_token(reauth=reauth)
  File "/home/pcholken/.local/lib/python3.9/site-packages/vk_api/vk_api.py", line 225, in _auth_token
    self._api_login()
  File "/home/pcholken/.local/lib/python3.9/site-packages/vk_api/vk_api.py", line 450, in _api_login
    params = response.url.split('#', 1)[1].split('&')
IndexError: list index out of range
```

**Comment by python273** [comment]
Должно работать в 11.9.2

`python3 -m pip install -U vk-api`

**Comment by python273** [comment]
@Pcholken и рекомендую поменять пароль

**Comment by python273** [comment]
Видимо ВК опять что-то поменял, 11.9.3

`python3 -m pip install -U vk-api`

**Comment by through-your-tears** [comment]
Та же самая проблема, не понятно, как исправлять
