### ISSUE TITLE
Проблемы с ввторизацией

### ISSUE THREAD

**Issue by Escalt4** [python273/vk_api#405]
_добавить описание_

### Окружение

vk_api: 11.9.3

API: _вставить версию_

### Пример

```python
Traceback (most recent call last):
  File "C:\Users\User\Desktop\1.py", line 12, in <module>
    vk_session.auth()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\vk_api\vk_api.py", line 180, in auth
    self._auth_cookies(reauth=reauth)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\vk_api\vk_api.py", line 211, in _auth_cookies
    self._api_login()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\vk_api\vk_api.py", line 457, in _api_login
    raise AuthError(get_unknown_exc_str('API AUTH; no access_token'))
vk_api.exceptions.AuthError: Unknown error (API AUTH; no access_token). Please send bugreport to GitHub or vk_api@python273.pw
```

**Comment by dashedman** [comment]
Да там теперь для `parsed_query['authorize_url'][0]` нужно использовать `unquote()` из `urllib.parse`

**Comment by Escalt4** [comment]
Спасибо [dashedman](https://github.com/python273/vk_api/issues/405#issuecomment-843972873) и [EugeneJenkins](https://github.com/python273/vk_api/issues/406#issuecomment-844108376), авторизация заработала. 
В файле `vk_api.py` который у меня лежит в `C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\vk_api` добавил импорт `from urllib.parse import urlparse, parse_qs, unquote` и заменил строку `parsed_url = urlparse(parsed_query['authorize_url'][0])` на `parsed_url = urlparse(unquote(parsed_query['authorize_url'][0]))`

**Comment by python273** [comment]
dup #406

Должно работать в 11.9.4

python3 -m pip install -U vk-api
