### ISSUE TITLE
Проблема загрузки файлов из io.BytesIO

### ISSUE THREAD

**Issue by edombek** [python273/vk_api#413]
_добавить описание_

### Окружение

vk_api: 11.9.4

API: не суть

### Пример

```python
def uploadDoc(filename, dat):
    file = io.BytesIO(dat)
    doc = upload.document_message(
        file,
        title=filename,
        peer_id=peer_id
    )
    file.close()
    return f"doc{doc['doc']['owner_id']}_{doc['doc']['id']},"
```
название файла и байты, отправка из фс по пути файла работает

### Ошибка
```python
Traceback (most recent call last):

  File "<ipython-input-10-71d5294a274e>", line 1, in <module>
    uploadDoc(fixFileExtent(filename), dat)

  File "/data/projects/mailtovkbot/mailtovkbot.py", line 32, in uploadDoc
    doc = upload.document_message(

  File "/home/edombek/.local/lib/python3.9/site-packages/vk_api/upload.py", line 441, in document_message
    return self.document(doc, title, tags, message_peer_id=peer_id)

  File "/home/edombek/.local/lib/python3.9/site-packages/vk_api/upload.py", line 417, in document
    return self.vk.docs.save(**response)

  File "/home/edombek/.local/lib/python3.9/site-packages/vk_api/vk_api.py", line 708, in __call__
    return self._vk.method(self._method, kwargs)

  File "/home/edombek/.local/lib/python3.9/site-packages/vk_api/vk_api.py", line 668, in method
    raise error

ApiError: [100] One of the parameters specified was missing or invalid: file is undefined
```

**Comment by edombek** [comment]
Решение примитивное:
```python
def uploadDoc(filename, dat):
    file = io.BytesIO(dat)
    file.name = filename
    doc = upload.document_message(
        file,
        title=filename,
        peer_id=peer_id
    )
    file.close()
    return f"doc{doc['doc']['owner_id']}_{doc['doc']['id']},"
```
