### ISSUE TITLE
Что то случилось с аутентификацией

### ISSUE THREAD

**Issue by kz159** [python273/vk_api#416]
### Окружение
vk_api: 11.9.1

API: простой пример из README не работает

### Пример
```
import vk_api

vk_session = vk_api.VkApi('+71234567890', 'mypassword')
vk_session.auth()

vk = vk_session.get_api()

print(vk.wall.post(message='Hello world!'))
```
выдает 
```
Traceback (most recent call last):
  File "/home/kz159/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/211.7628.24/plugins/python-ce/helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/home/kz159/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/211.7628.24/plugins/python-ce/helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/kz159/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/211.7628.24/plugins/python-ce/helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/kz159/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/211.7628.24/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/kz159/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/211.7628.24/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/__main__.py", line 12, in <module>
    main()
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/__main__.py", line 8, in main
    account = get_account()
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/account.py", line 145, in get_account
    account = Account(tg_kwargs, vk_kwargs)
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/account.py", line 34, in __init__
    self.setup()
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/account.py", line 37, in setup
    self.vk.auth()
  File "/home/kz159/.pyenv/versions/monetizer/lib/python3.9/site-packages/vk_api/vk_api.py", line 175, in auth
    self._auth_cookies(reauth=reauth)
  File "/home/kz159/.pyenv/versions/monetizer/lib/python3.9/site-packages/vk_api/vk_api.py", line 206, in _auth_cookies
    self._api_login()
  File "/home/kz159/.pyenv/versions/monetizer/lib/python3.9/site-packages/vk_api/vk_api.py", line 449, in _api_login
    params = response.url.split('#', 1)[1].split('&')
IndexError: list index out of range
```

**Comment by kz159** [comment]
Если проставить 0, то проблемы на этом не закончатся
```
Traceback (most recent call last):
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/account.py", line 112, in run
    self._run_forever()
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/account.py", line 107, in _run_forever
    self._check_and_restore_threads()
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/account.py", line 63, in _check_and_restore_threads
    self.check_collectors()
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/account.py", line 71, in check_collectors
    collector = self.collector_class(group_id=group_id,
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/vk_scrapper/collector.py", line 33, in __init__
    self.setup()
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/vk_scrapper/collector.py", line 36, in setup
    self.calculate_likes()
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/vk_scrapper/collector.py", line 47, in calculate_likes
    posts = self.get_posts(amount=100)
  File "/home/kz159/code/my/vk_normie_monetizer/monetizer/vk_scrapper/collector.py", line 57, in get_posts
    vk_get_post_result = self.vk_api.wall.get(owner_id=self.group_id,
  File "/home/kz159/.pyenv/versions/monetizer/lib/python3.9/site-packages/vk_api/vk_api.py", line 696, in __call__
    return self._vk.method(self._method, kwargs)
  File "/home/kz159/.pyenv/versions/monetizer/lib/python3.9/site-packages/vk_api/vk_api.py", line 607, in method
    values['access_token'] = self.token['access_token']
KeyError: 'access_token'
```

**Comment by python273** [comment]
`python3 -m pip install -U vk-api`
