### ISSUE TITLE
Рандомная ошибка vk_api.exceptions.AuthError при reauth=True

### ISSUE THREAD

**Issue by Pro100rus32** [python273/vk_api#421]
**Code:**
```
import vk_api
login, password = "Log", "Pas"
vk_session = vk_api.VkApi(login, password, config_filename="config_vk.json")
vk_session.auth(reauth=True)
```

**Output:**
```
Traceback (most recent call last):
  File "D:\test\test.py", line 4, in <module>
    vk_session.auth(reauth=True)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\vk_api\vk_api.py", line 180, in auth
    self._auth_cookies(reauth=reauth)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\vk_api\vk_api.py", line 189, in _auth_cookies
    self._vk_login()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\vk_api\vk_api.py", line 309, in _vk_login
    raise AuthError(get_unknown_exc_str('AUTH; no sid'))
vk_api.exceptions.AuthError: Unknown error (AUTH; no sid). Please send bugreport to GitHub or vk_api@python273.pw
```

**Такое ощущение, что при частых запросах я получаю эту ошибку. Но она появляется и при первом запросе, если я не вызывал его до этого несколько минут, иногда.** 

**Без `reauth=True`, всё работает как часы.**

**Comment by python273** [comment]
`reauth` игнорирует сохранненые куки и токен и получает их занво. Скорее всего из-за этого капча начинает вылезать

Лучше всего пользоваться `auth(token_only=True)`, так при запуске только токен проверяется
