### ISSUE TITLE
Не возможно авторизоваться при использовании прокси

### ISSUE THREAD

**Issue by ZhekaLavrov** [python273/vk_api#438]
**Не возможно авторизоваться при использовании прокси**
Traceback (most recent call last):
  File "C:\Users\evgen\PycharmProjects\ProxyTest\vk.py", line 13, in <module>
    vk_session.auth()
  File "C:\Users\evgen\PycharmProjects\ProxyTest\venv\lib\site-packages\vk_api\vk_api.py", line 181, in auth
    self._auth_cookies(reauth=reauth)
  File "C:\Users\evgen\PycharmProjects\ProxyTest\venv\lib\site-packages\vk_api\vk_api.py", line 201, in _auth_cookies
    self._vk_login()
  File "C:\Users\evgen\PycharmProjects\ProxyTest\venv\lib\site-packages\vk_api\vk_api.py", line 325, in _vk_login
    raise AuthError(get_unknown_exc_str('AUTH; no sid'))
vk_api.exceptions.AuthError: Unknown error (AUTH; no sid). Please send bugreport to GitHub or vk_api@python273.pw

### Окружение

vk_api: 11.9.6

API: 5.131

### Пример

```python
import requests
import vk_api
from proxy_info import login, password

proxies = {
    'https': f'http://{login}:{password}@proxy_ip:proxy_port'
}
session = requests.session()
session.proxies.update(proxies)

vk_session = vk_api.VkApi('login', 'password', session=session, app_id=6287487, api_version="5.131")
vk_session.auth()


```

**Comment by MrTransistorsChannel** [comment]
Связано с #437 и возможно #432

**Comment by M1h4n1k** [comment]
Предположительно - появляется капча, а библиотека это не может определить, поэтому падает. 
(Вставил в мазилу прокси и попробовал войти в аккаунт с проксями и кредами, которые вызывали ошибку)

![изображение](https://user-images.githubusercontent.com/82715719/179062744-d8a7fa3a-863d-42ff-87f9-7ecfb764aff6.png)

**Comment by CrazyNeron** [comment]
Решение этой проблемы есть?
