### ISSUE TITLE
[RU][FIXED] Recaptcha required

### ISSUE THREAD

**Issue by Ktezor** [python273/vk_api#460]
_Поломался вход в пользовательский аккаунт. Раньше вход работал. Как я понял, пересылает на Recaptcha. Может, я чего-то уже не понимаю?
Ранее ругалось на remixsid. После удаления старых json файлов, вроде, больше не видел_

### Окружение

vk_api: 11.9.7

Без API для бота (используется вход через логин и пароль)

### Пример (упрощённый)

```python
from vk_api import VkApi
import mestidy # условно в нём есть расширение над VkApi, но для полноты будем использовать обычный

def get_password():
    return input("Login: "), input("Password: ")

_login, _password = get_password()
vk_session = vk_api.VkApi(login = _login, password = _password, captcha_handler = mestidy.captcha_handler, auth_handler = mestidy.auth_handler) # ещё указывается app_id
try:
    vk_session.auth() # ошибка авторизации
exception: ...
```
### Полный трейс
```
Traceback (most recent call last):
  File "C:\...\my_bot\main.py", line 5, in <module>
    bot = Bot()
  File "C:\...\my_bot\bot.py", line 10, in __init__
    api.auth()
  File "C:\...\my_bot\mestidy\mestidyApi.py", line 59, in _gui_auth
    if exceptions_treatment(self.vk_session.auth)[1]:
  File "C:\...\my_bot\mestidy\mestidyApi.py", line 20, in exceptions_treatment
    return function_auth(*args, **kwargs), True
  File "C:\...\Python310\lib\site-packages\vk_api\vk_api.py", line 184, in auth
    self._auth_cookies(reauth=reauth)
  File "C:\...\Python310\lib\site-packages\vk_api\vk_api.py", line 204, in _auth_cookies
    self._vk_login()
  File "C:\...\Python310\lib\site-packages\vk_api\vk_api.py", line 322, in _vk_login
    self._pass_twofactor(response)
  File "C:\...\Python310\lib\site-packages\vk_api\vk_api.py", line 372, in _pass_twofactor
    raise TwoFactorError('Recaptcha required')
vk_api.exceptions.TwoFactorError: Recaptcha required
```

**Comment by Ktezor** [comment]
After last update it was fixed. Thx
