### ISSUE TITLE
Невозможно авторизоваться .

### ISSUE THREAD

**Issue by vega0** [python273/vk_api#481]
_добавить описание_

### Окружение

vk_api: 11.9.9

API: нету

### Пример
```
vk_session = vk_api.VkApi(login, password)
vk_session .auth()
```

Ошибка, отчет.

```
Traceback (most recent call last):
  File "F:\Рабочее Пространство\!Машинный\python.machinarium\vk_test_database.py", line 7, in <module>
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Рабочее Пространство\!Машинный\python.machinarium\Machinarium\Classes\Vk\__main__.py", line 45, in __init__
    self.vk_session.auth()
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\vk_api\vk_api.py", line 187, in auth
    self._auth_cookies(reauth=reauth)
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\vk_api\vk_api.py", line 207, in _auth_cookies
    self._vk_login()
  File "D:\Users\Koshmar\AppData\Local\Programs\Python\Python311\Lib\site-packages\vk_api\vk_api.py", line 338, in _vk_login
    raise AuthError(get_unknown_exc_str('AUTH; no sid'))
vk_api.exceptions.AuthError: Unknown error (AUTH; no sid). Please send a bugreport to GitHub: https://github.com/python273/vk_api/issues
```

**Comment by mb6ockatf** [comment]
У меня такая же ошибка.
```python
Traceback (most recent call last):
  File "/home/username/projects/app/./app.py", line 206, in <module>
    main()
  File "/home/username/projects/app/./app.py", line 198, in main
    downloader = MusicDownloader(login=login, password=password)
  File "/home/username/projects/app/./app.py", line 26, in __init__
    self._vk_session.auth()
  File "/home/username/projects/app/venv/lib/python3.10/site-packages/vk_api/vk_api.py", line 187, in auth
    self._auth_cookies(reauth=reauth)
  File "/home/username/projects/app/venv/lib/python3.10/site-packages/vk_api/vk_api.py", line 207, in _auth_cookies
    self._vk_login()
  File "/home/username/projects/app/venv/lib/python3.10/site-packages/vk_api/vk_api.py", line 338, in _vk_login
    raise AuthError(get_unknown_exc_str('AUTH; no sid'))
vk_api.exceptions.AuthError: Unknown error (AUTH; no sid). Please send a bugreport to GitHub: https://github.com/python273/vk_api/issues
```

**Comment by dkzmn** [comment]
Тоже, началось 6 июня 2023

Python 3.5:
 File "/home/test.py", line 23, in <module>
    vk_session.auth()
  File "/usr/local/lib/python3.5/dist-packages/vk_api/vk_api.py", line 180, in auth
    self._auth_cookies(reauth=reauth)
  File "/usr/local/lib/python3.5/dist-packages/vk_api/vk_api.py", line 200, in _auth_cookies
    self._vk_login()
  File "/usr/local/lib/python3.5/dist-packages/vk_api/vk_api.py", line 309, in _vk_login
    raise AuthError(get_unknown_exc_str('AUTH; no sid'))
vk_api.exceptions.AuthError: Unknown error (AUTH; no sid). Please send bugreport to GitHub or vk_api@python273.pw

Python 3.9:
Traceback (most recent call last):
  File "/home/test.py", line 23, in <module>
    vk_session.auth()
  File "/usr/local/lib/python3.9/site-packages/vk_api/vk_api.py", line 187, in auth
    self._auth_cookies(reauth=reauth)
  File "/usr/local/lib/python3.9/site-packages/vk_api/vk_api.py", line 218, in _auth_cookies
    self._api_login()
  File "/usr/local/lib/python3.9/site-packages/vk_api/vk_api.py", line 516, in _api_login
    raise AuthError('Unknown API auth error')
vk_api.exceptions.AuthError: Unknown API auth error

**Comment by rootkit-sys** [comment]
Тоже самое

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\buba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\vk_api\vk_api.py", line 187, in auth
    self._auth_cookies(reauth=reauth)
  File "C:\Users\buba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\vk_api\vk_api.py", line 218, in _auth_cookies
    self._api_login()
  File "C:\Users\buba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\vk_api\vk_api.py", line 516, in _api_login
    raise AuthError('Unknown API auth error')
vk_api.exceptions.AuthError: Unknown API auth error
`

**Comment by mb6ockatf** [comment]
@vega0 проект, видимо, умер. ребята из вк не умеют в обратную совместимость api, к сожалению

наверное, можно закрыть issue как `never fix`

**Comment by egorka-angelskiy** [comment]
vk_session = vk_api.VkApi(login, password, app_id=2685278)

Используйте данную версию, тогда все будет отлично

**Comment by chebotarevmichael** [comment]
как раз ищу какую задачку сделать)) постараюсь посмотреть и решить

**Comment by Danspers** [comment]
> vk_session = vk_api.VkApi(login, password, app_id=2685278)
> 
> Используйте данную версию, тогда все будет отлично

Егор, спасибо за подсказку! Оказывается, что параметр app_id - обязательный, который содержит номер Standalone-приложение необходимого для авторизации. Исходя из [документации](https://vk-api.readthedocs.io/en/latest/_modules/vk_api/vk_api.html#VkApi), по умолчанию app_id=6222115, которое не работает.

В свою очередь app_id=2685278 работает, только возникает вопросы откуда этот номер? Если возможность найти о нём информацию? Можно ли доверять этому приложению или лучше создать своё?

[Создать](https://vk.com/editapp?act=create) собственное приложение и получить app_id - возможно, но этого недостаточно. Необходимо дополнительно его настроить, с чем я ещё не разобрался.

**Comment by OstrovCity** [comment]
app_id=2685278 - это приложение Kate Mobile. Можно ещё использовать app_id=6287487 - это ВКонтакте API

**Comment by Danspers** [comment]
Да, так оно и есть этот id от Kate Mobile - неофициальная моб. приложения для ВКонтакте.

Основная проблема заключалась в неактуальной библиотеке[ vk_api](https://github.com/python273/vk_api) для Python. Несмотря на то, что использовалась последняя релизная версия (11.9.9 от 25 июля 2022), она претерпела важные изменения. В том числе процедуры авторизации. Но эти обновления не попали в релиз и доступны только в версии опубликованной на GitHub.

В моём случае было принято решение воспользоваться [VKBottle](https://github.com/vkbottle/vkbottle). Вариант посвежее будет.
