### ISSUE TITLE
VkAudio не может найти аудиозаписи. IndexError: list index out of range

### ISSUE THREAD

**Issue by TheSaintDiratof** [python273/vk_api#495]
При попытке вызвать функцию VkAudio(VkApi(token=usertoken)).search(q="гроб") выдаёт ошибку IndexError: list index out of range.
VkApi вызываю с токеном пользователя

### Окружение
OS: Gentoo Linux
Python: 3.11.5 (main, Sep 14 2023, 16:27:58) [Clang 16.0.6 ] on linux
vk_api: 11.9.9
API: 5.131

### Пример
vk = VkApi(token=usertoken)
vkAudio(vk).search(q="гроб")
```
### Ошибка
Traceback (most recent call last):
  File "/home/diratof/Documents/kwork/170923_pybot/main.py", line 863, in <module>
    music_search(peer_id, text)
  File "/home/diratof/Documents/kwork/170923_pybot/main.py", line 165, in music_search
    print(list(music))
          ^^^^^^^^^^^
  File "/home/diratof/Documents/kwork/170923_pybot/venv/lib/python3.11/site-packages/vk_api/audio.py", line 347, in search_iter
    while json_response['payload'][1][1]['playlist']:
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by python273** [comment]
для VkAudio нужны куки
