### ISSUE TITLE
AuthError

### ISSUE THREAD

**Issue by alkopit** [python273/vk_api#501]
При запуске вываливает ошибка "vk_api.exceptions.BadPassword: Bad password", авторизация не происходит.
Если в логин добавить перед номером + то вываливается ошибка "vk_api.exceptions.AuthError: Unknown API auth error", происходит авторизация, в приложении VK появляется событие с сообщением о успешном входе.
Логин и пароль верные.

### Окружение
Win10
Python 3.12.0
vk_api: 11.9.9

### Пример
```python
import vk_api
vk_session = vk_api.VkApi("79685554422", "Password652")
vk_session.auth()
vk = vk_session.get_api()
print("DONE!")
```
Traceback (most recent call last):
  File "C:\py_ed\dw_helper\test_api.py", line 4, in <module>
    vk_session.auth()
  File "C:\py_ed\dw_helper\winenv\Lib\site-packages\vk_api\vk_api.py", line 187, in auth
    self._auth_cookies(reauth=reauth)
  File "C:\py_ed\dw_helper\winenv\Lib\site-packages\vk_api\vk_api.py", line 207, in _auth_cookies
    self._vk_login()
  File "C:\py_ed\dw_helper\winenv\Lib\site-packages\vk_api\vk_api.py", line 323, in _vk_login
    raise BadPassword('Bad password')
vk_api.exceptions.BadPassword: Bad password

```python
import vk_api
vk_session = vk_api.VkApi("+79685554422", "Password652")
vk_session.auth()
vk = vk_session.get_api()
print("DONE!")
```
Traceback (most recent call last):
  File "C:\py_ed\dw_helper\test_api.py", line 4, in <module>
    vk_session.auth()
  File "C:\py_ed\dw_helper\winenv\Lib\site-packages\vk_api\vk_api.py", line 187, in auth
    self._auth_cookies(reauth=reauth)
  File "C:\py_ed\dw_helper\winenv\Lib\site-packages\vk_api\vk_api.py", line 218, in _auth_cookies
    self._api_login()
  File "C:\py_ed\dw_helper\winenv\Lib\site-packages\vk_api\vk_api.py", line 516, in _api_login
    raise AuthError('Unknown API auth error')
vk_api.exceptions.AuthError: Unknown API auth error

**Comment by M1h4n1k** [comment]
Тут соседнее ишью с похожей проблемой. попробуй форк, мб поможет

https://github.com/python273/vk_api/issues/496#issuecomment-1937560168

**Comment by alkopit** [comment]
> Тут соседнее ишью с похожей проблемой. попробуй форк, мб поможет
> 
> [#496 (comment)](https://github.com/python273/vk_api/issues/496#issuecomment-1937560168)

В общем надо с гита брать репу, а не через pip vk_api.
Тогда всё норм. 
в #498 [Danspers] верно написал. На pypi не обновлена репа.

**Comment by M1h4n1k** [comment]
> > Тут соседнее ишью с похожей проблемой. попробуй форк, мб поможет
> > [#496 (comment)](https://github.com/python273/vk_api/issues/496#issuecomment-1937560168)
> 
> В общем надо с гита брать репу, а не через pip vk_api. Тогда всё норм. в #498 [Danspers] верно написал. На pypi не обновлена репа.

хз я пытался, у меня не работало

**Comment by Shirel-s** [comment]
я тоже пробовала брать репу с гита и не помогло. кто-нибудь нашел другое решение?
