### ISSUE TITLE
Can't login to account with login and password

### ISSUE THREAD

**Issue by internetrvze** [python273/vk_api#505]
При попытке войти в аккаунт ВК по логину паролю мне выбрасывает ошибку:
```
vk_api.exceptions.AuthError: Unknown API auth error
```
При этом с авторизацией по токену модуль работает штатно.

### Окружение
vk_api: 11.9.9
API: 5.131

### Пример
```python
from vk_api import VkApi

login = input('[-] Enter login: ')
password = input('[-] Enter password: ')

def auth():
    return input('[-] Enter 2FA code: '), True

session = VkApi(
    login, password, 
    auth_handler=auth,
    api_version='5.131', 
    app_id=2685278  # Ошибка происходит всегда, вне зависимости от установленного APP ID
)
session.auth()

api = session.get_api()
```

```
[-] Enter login: +71234567890
[-] Enter password: password
[-] Enter 2FA code: 816405
Traceback (most recent call last):
  File "C:\Users\rvze\Desktop\vk.py", line 15, in <module>
    session.auth()
  File "C:\Users\rvze\AppData\Local\Programs\Python\Python312\Lib\site-packages\vk_api\vk_api.py", line 187, in auth
    self._auth_cookies(reauth=reauth)
  File "C:\Users\rvze\AppData\Local\Programs\Python\Python312\Lib\site-packages\vk_api\vk_api.py", line 218, in _auth_cookies
    self._api_login()
  File "C:\Users\rvze\AppData\Local\Programs\Python\Python312\Lib\site-packages\vk_api\vk_api.py", line 516, in _api_login
    raise AuthError('Unknown API auth error')
vk_api.exceptions.AuthError: Unknown API auth error
```

**Comment by waslost0** [comment]
@internetrvze Можешь попробовать мои изменения https://github.com/python273/vk_api/pull/506

**Comment by internetrvze** [comment]
> @internetrvze Можешь попробовать мои изменения #506

![image](https://github.com/python273/vk_api/assets/65215768/cbf6bb0b-47a0-4655-8b9d-a788a927b294)

**Comment by M1h4n1k** [comment]
Вот эта не работает? 
https://github.com/M1h4n1k/vk_api_fix_auth
