### ISSUE TITLE
Unknown API auth error

### ISSUE THREAD

**Issue by KweezyCode** [python273/vk_api#513]
```
from vk_api.vk_api import VkApiMethod, VkApi

vk_session = VkApi('+xxx', 'xxx')

vk_session.auth()

vk: VkApiMethod = vk_session.get_api()
```

(xxx) "xxx/bin/python" "xxx/main.py"
Traceback (most recent call last):
  File "xxx/main.py", line 7, in <module>
    vk_session.auth()
  File "xxx/lib/python3.11/site-packages/vk_api/vk_api.py", line 187, in auth
    self._auth_cookies(reauth=reauth)
  File "xxx/lib/python3.11/site-packages/vk_api/vk_api.py", line 218, in _auth_cookies
    self._api_login()
  File "xxx/lib/python3.11/site-packages/vk_api/vk_api.py", line 516, in _api_login
    raise AuthError('Unknown API auth error')
vk_api.exceptions.AuthError: Unknown API auth error

**Comment by username391** [comment]
pip uninstall vk-api
pip install git+https://github.com/python273/vk_api

**Comment by KweezyCode** [comment]
> pip uninstall vk-api pip install git+https://github.com/python273/vk_api

vk-api looks dead, i am using vkbottle right now

**Comment by freQuensy23-coder** [comment]
Same issue(
