### ISSUE TITLE
vk_api.longpoll: KeyError: 'pts'

### ISSUE THREAD

**Issue by gorinovdan** [python273/vk_api#514]
Ошибка при запуске user longpoll. Уже запущенные сессии продолжают работать.

```
Traceback (most recent call last):
  File "C:\Users\Asuse\Documents\Study\OtherProjects\WDB\OtherTest.py", line 97, in <module>
    longpoll = VkLongPoll(vk_session)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asuse\Documents\Study\OtherProjects\WDB\.venv\Lib\site-packages\vk_api\longpoll.py", line 511, in __init__
    self.update_longpoll_server()
  File "C:\Users\Asuse\Documents\Study\OtherProjects\WDB\.venv\Lib\site-packages\vk_api\longpoll.py", line 535, in update_longpoll_server
    self.pts = response['pts']
               ~~~~~~~~^^^^^^^
KeyError: 'pts'
```

### Окружение

vk_api: 11.9.9

API: default (5.92)

### Пример

```python
vk_session = vk_api.VkApi(token=TOKEN)
longpoll = VkLongPoll(vk_session)
```

**Comment by ShishkaDanil** [comment]
Ща законтрибьючу

**Comment by AnakhSun** [comment]
решение:
 [(pull reqest #515)](https://github.com/python273/vk_api/pull/515)

**Comment by python273** [comment]
pts не шлют иногда теперь или там это нужно как-то правильно обрабатывать?

**Comment by AnakhSun** [comment]
Теперь иногда не шлют

**Comment by dementidesu** [comment]
Поставил mode=1 и заработало. Не знаю, как на работе в целом отразиться, но хотя бы без этого бага
