### ISSUE TITLE
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

### ISSUE THREAD

**Issue by yzinets** [python273/vk_api#86]
Являюсь жителем Украины. Выдаёт такой вот traceback при попытке авторизации. Пытаюсь подсунуть сессию, привязанную на Tor. Результат тот же. SOCKSPort 14000 указан верно, ip берёт правильно. Если есть возможность помочь с этим вопросом, буду рад.
```
# Init Tor session
s = TorSession()
session = requests.Session()
session.proxies = {
    'http': 'socks5://127.0.0.1:14000', 
    'https': 'socks5://127.0.0.1:14000'
}
# Init vk api instance and replace session
api = vk_api.VkApi(login=args.login, password=args.password)
api.http = session
# Auth
api.auth()
```

**Comment by python273** [comment]
Попробуй установить прокси в `api.http.proxies`

Еще посмотри выводит ли твой IP `print(session.get('https://httpbin.org/ip').text)`

**Comment by yzinets** [comment]
```
import requests
import vk_api


print(requests.get("https://httpbin.org/ip").text)

session = requests.Session()
session.proxies = {
    "http": "socks5://127.0.0.1:14000",
    "https": "socks5://127.0.0.1:14000",
}

print(session.get("https://httpbin.org/ip").text)

api = vk_api.VkApi(login="...", password="...")
api.http.proxies = {
    "http": "socks5://127.0.0.1:14000",
    "https": "socks5://127.0.0.1:14000",
}
api.auth()
```
Вывод:  
```
{
  "origin": "195.114.136.192"
}

{
  "origin": "79.137.79.167"
}

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yzinets/Projects/zombieland-vk/test.py", line 20, in <module>
    api.auth()
  File "/usr/local/lib/python3.5/dist-packages/vk_api/vk_api.py", line 158, in auth
    self._auth_cookies(reauth=reauth)
  File "/usr/local/lib/python3.5/dist-packages/vk_api/vk_api.py", line 180, in _auth_cookies
    self.vk_login()
  File "/usr/local/lib/python3.5/dist-packages/vk_api/vk_api.py", line 230, in vk_login
    response = self.http.get('https://vk.com/')
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 531, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 512, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

Process finished with exit code 1
```

**Comment by python273** [comment]
Попробуй установить `requests[security]`

У меня работает с этим кодом:
```
# -*- coding: utf-8 -*-
import vk_api


def main():
    vk_session = vk_api.VkApi('L', 'P')

    vk_session.http.proxies = {
        'http': 'socks5://127.0.0.1:9050/',
        'https': 'socks5://127.0.0.1:9050/'
    }
    vk_session.auth()

if __name__ == '__main__':
    main()
```
